# Site settings
title: James's sharing
email: sunnypengfei@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
     keep learning and sharing!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://spengfei.github.io/" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: spengfei

# Build settings
markdown: kramdown
